/*<?xml version="1.0" encoding="UTF-8" standalone="no"?><header>*/
/* <!-- */
//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.

#ifndef BAT811CPPPROJECT_NAMESPACE_sampleimpl_wrapper_h_
#define BAT811CPPPROJECT_NAMESPACE_sampleimpl_wrapper_h_

#if defined(WIN32) || defined (_WINDOWS)
#pragma warning(disable: 4786)
#endif 

#include "application/TibAmxApplicationDefinitions.h"
#include "application/SampleImpl.h"
#include "tibamx/databinding/cppdom/xml/IntegerTypes.h"
#include "tibamxcpp/core/Wrapper.h"
#include "tibamxcpp/core/Application.h"
#include "tibamx/databinding/cppdom/serializers/Serializers.h"
#include <xercesc/dom/DOM.hpp>
#define BAT811CPPPROJECT_NAMESPACE SampleNamespace

namespace BAT811CPPPROJECT_NAMESPACE
{
	class SampleImpl_Wrapper : public TIBAMX_CPP_NAMESPACE::Wrapper
	{
	public:

		SampleImpl_Wrapper(TIBAMX_CPP_NAMESPACE::Application& appImpl) : TIBAMX_CPP_NAMESPACE::Wrapper(appImpl){}

		~SampleImpl_Wrapper(){}
				
		virtual void invoke(TIBAMX_CPP_NAMESPACE::Operation& operation) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException);
		
	private:
		/* -->
		<constantVariablesSection>
		<service generated="YES" name="WSDL_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::AddressRemotePortTypeService">
		<!--*/

		static const XMLCh* NS_ADDRESSREQUESTRESPONSE;
		static const XMLCh* ADDRESSREQUESTARGS0;
		static const XMLCh* HTTP___COMPANYADDRESS_IQATEST_EJBBT_AMX_TIBCO_COM;
		static const XMLCh* NS_ADDRESSREQUEST;
		static const XMLCh* NS_REMOTEEXCEPTION;
		/*-->
		</service>
		</constantVariablesSection>
		<!-- */
	};
} //Closing of BAT811CPPPROJECT_NAMESPACE
#endif // SampleImpl_Wrapper_h
/* --> */
//</header>
