/*<?xml version="1.0" encoding="UTF-8"?><header>*/
/* <!-- */
//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.

#include "SampleImpl_ApplicationFactory.h"
#include "SampleImpl_Wrapper.h"
#define BAT811CPPPROJECT_NAMESPACE SampleNamespace
/* -->
<includeSection>
</includeSection>
<!-- */

namespace BAT811CPPPROJECT_NAMESPACE
{
	extern "C"
	{

	#if defined(WIN32) || defined(_WINDOWS)
		__declspec(dllexport) 
	#endif
		SampleImpl_ApplicationFactory* get_SampleImpl_ApplicationFactory()
		{
			return new SampleImpl_ApplicationFactory();
		}
	}

	SampleImpl_ApplicationFactory::SampleImpl_ApplicationFactory()
	{
		cx_appImpl = new SampleImpl();
	}

	SampleImpl_ApplicationFactory::~SampleImpl_ApplicationFactory()
	{
		if(cx_appImpl != NULL) { delete cx_appImpl; }
	}

	TIBAMX_CPP_NAMESPACE::Wrapper* SampleImpl_ApplicationFactory::getServiceWrapper() const
	{
		return new SampleImpl_Wrapper(*cx_appImpl);
	}
	
	TIBAMX_CPP_NAMESPACE::Wrapper* SampleImpl_ApplicationFactory::getReferenceWrapper(const std::string& referenceName) const
	{
		/* -->
		<generatedSection>
		</generatedSection>
		<!-- */
		return NULL;
	}
} //END of BAT811CPPPROJECT_NAMESPACE
/* --> */
//</header>
