/*<?xml version="1.0" encoding="UTF-8" standalone="no"?><header>*/
/* <!-- */
//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.
#ifndef SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE_ABSTRACTSAMPLEIMPL_H_
#define SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE_ABSTRACTSAMPLEIMPL_H_

#include "application/TibAmxApplicationDefinitions.h"
#include "tibamxcpp/utils/TibAmxCppDefinitions.h"
#include "tibamxcpp/core/Application.h"
#include "tibamx/databinding/cppdom/xml/TibcoXmlTypes.h"
#include "tibamx/core/TibcoRuntimeException.h"
#include "tibamx/databinding/cppdom/serializers/Serializers.h"
#include <xercesc/dom/DOM.hpp>
#include <vector>
#define SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE SampleNamespace
/* -->
<includeSection>
<interface generated="YES" name="AllMEPsWSDLFileinterface.h">
<!--*/
#include "wsdl_org_example_www_allmepswsdlfile/AllMEPsWSDLFileInterface.h"
/*-->
</interface>
<portTypeInclude generated="YES" name="WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::AllMEPsWSDLFileService">
<!--*/
#include "xsd_org_example_www_allmepswsdlfile/NewOperationFault_dataFault.h"
#include "xsd_org_example_www_allmepswsdlfile/NewOperation_dataElement.h"
#include "xsd_org_example_www_allmepswsdlfile/NewOperationResponse_dataElement.h"
/*-->
</portTypeInclude>
<referenceProxyInclude generated="YES" name="AllMEPsWSDLFileAllMEPsWSDLFileProxy.h">
<!--*/
#include "wsdl_org_example_www_allmepswsdlfile/AllMEPsWSDLFileAllMEPsWSDLFileProxy.h"
/*-->
</referenceProxyInclude>
<portType generated="YES" name="WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::AllMEPsWSDLFileReference">
<!--*/
/*-->
</portType>
</includeSection>
<!-- */
namespace SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE
{
	class AbstractSampleImpl : public TIBAMX_CPP_NAMESPACE::Application
			/* --><InheritanceDefinitions>
			<publicInterface generated="YES" name="WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::AllMEPsWSDLFile">
			<!--*/
			, public WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::AllMEPsWSDLFileInterface
			/*-->
			</publicInterface>
			</InheritanceDefinitions><!-- */
	{
	private:

		/* -->
		<MemberVariables>
		<referenceProxy generated="YES" name="AllMEPsWSDLFile_proxy">
		<!--*/
		WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::AllMEPsWSDLFileAllMEPsWSDLFileProxy allMEPsWSDLFile_proxy; 
		/*-->
		</referenceProxy>
		<propertyDefinition generated="YES" name="libpath">
		<!--*/
		std::string libpath; 
		/*-->
		</propertyDefinition>
		</MemberVariables>
		<!-- */

		/* -->
		<privateSection>
		<propertySetter generated="YES" name="libpath">
		<!--*/
		void setLibpath(const std::string & cx_value)
		{
			libpath = cx_value;
		}/*-->
		</propertySetter>
		</privateSection>
		<!-- */

	public:
		AbstractSampleImpl() {}
		virtual ~AbstractSampleImpl() {}

		/*	
		 * Add initialization code here. This method is called once during component initialization.
		 */
		virtual void init() throw (TIBAMX_CORE_NAMESPACE::ApplicationException){}

		/*	
		 * Add finalization code here. This method is called once during component destruction.
		 */
		virtual void destroy() throw (TIBAMX_CORE_NAMESPACE::ApplicationException){}

	 /*	
	  * Sets the properties in the application.
	  */
	 void setProperties(std::vector<TIBAMX_CORE_NAMESPACE::Property*>& cx_properties )
	 {
		 std::vector<TIBAMX_CORE_NAMESPACE::Property*>::iterator cx_it;
		 for (cx_it = cx_properties.begin(); cx_it != cx_properties.end(); cx_it++ )
		 {
	 	/* -->
	 	<propertySelector>
	 	<propety generated="YES" name="libpath">
		<!--*/
		if((*cx_it)->getName() == "libpath") 
		{
			setLibpath(*((*cx_it)->getValue<std::string>()));
		}
		/*-->
		</propety>
		</propertySelector>
	 	<!-- */
		 }
	 }

		/* -->
		<publicSection>
		<referenceProxyGetterSetter generated="YES" name="AllMEPsWSDLFile_proxy">
		<!--*/
		WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::AllMEPsWSDLFileAllMEPsWSDLFileProxy& getAllMEPsWSDLFile_proxy()
		{
			allMEPsWSDLFile_proxy.setComponentContext(&m_componentContext);
			return allMEPsWSDLFile_proxy;
		}
		/*-->
		</referenceProxyGetterSetter>
		<propertyGetter generated="YES" name="libpath">
		<!--*/
		const std::string & getLibpath() const
		{
			return libpath;
		}
		/*-->
		</propertyGetter>
		</publicSection>
		<!-- */

	}; //END of AbstractSampleImpl
} //END of SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE

#endif
/* --> */
//</header>
