//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.
#include "NewOperationFault_dataFault.h"

namespace XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE
{
	NewOperationFault_dataFault::NewOperationFault_dataFault()
	{
		this->t_value = new XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement();
	}

	NewOperationFault_dataFault::NewOperationFault_dataFault(XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement& value) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException)
	{
		this->t_value = new XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement(value);
	}

	NewOperationFault_dataFault::NewOperationFault_dataFault(const NewOperationFault_dataFault & obj)
	{
		this->t_value = new XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement(*obj.t_value);
	}

	NewOperationFault_dataFault::~NewOperationFault_dataFault()
	{
		if(this->t_value != NULL) delete this->t_value;
	}

	const XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement& NewOperationFault_dataFault::get_value() const
	{
		return *t_value;
	}

	void NewOperationFault_dataFault::set_value(XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement& val)
	{
		*t_value = val;
	}

	NewOperationFault_dataFault & NewOperationFault_dataFault::operator=(const NewOperationFault_dataFault & obj)
	{
		if (this != &obj)
		{
			delete this->t_value;
			this->t_value = new XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement(*obj.t_value);
		}
		return (*this);
	}

	void NewOperationFault_dataFaultSerializer::serialize(XERCES_CPP_NAMESPACE::DOMElement* element, const void* parameter, TIBAMX_CORE_NAMESPACE::Context* context)  throw (TIBAMX_CORE_NAMESPACE::ServiceDataException)
	{
		const NewOperationFault_dataFault* tk = (NewOperationFault_dataFault*)parameter;
		const XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement& value = tk->get_value();
		XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElementSerializer::serialize(element, (void*)&value, context);
	}
	
	std::string NewOperationFault_dataFaultSerializer::serialize(const void* input, TIBAMX_CORE_NAMESPACE::Context* context)  throw (TIBAMX_CORE_NAMESPACE::ServiceDataException)
	{
		const NewOperationFault_dataFault* tk = (NewOperationFault_dataFault*)input;
		const XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement& value = tk->get_value();
		return XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElementSerializer::serialize((void*)&value, context);
	}
	
	void* NewOperationFault_dataFaultSerializer::deserialize(TIBAMX_CORE_NAMESPACE::DOMElementIterator& elementItr, void* parameter, TIBAMX_CORE_NAMESPACE::Context* context)  throw (TIBAMX_CORE_NAMESPACE::ServiceDataException)
	{
		NewOperationFault_dataFault* paramValue = (parameter == NULL)?	new NewOperationFault_dataFault() :(NewOperationFault_dataFault*)parameter;
		XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement* value = (XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement*)XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElementSerializer::deserialize(elementItr, NULL, context);
		paramValue->set_value(*value);

		delete value;
		return (void*)paramValue;
	}
	
	void* NewOperationFault_dataFaultSerializer::deserialize(const std::string& inputString, void* returnValue, TIBAMX_CORE_NAMESPACE::Context* context) throw (TIBAMX_CORE_NAMESPACE::ServiceDataException){
		NewOperationFault_dataFault* paramValue = (returnValue == NULL)?	new NewOperationFault_dataFault() :(NewOperationFault_dataFault*)returnValue;
		XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement* value = (XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElement*)XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataElementSerializer::deserialize(inputString, NULL, context);
		paramValue->set_value(*value);

		delete value;
		return (void*)paramValue;
	}

}
TIBAMX_CORE_NAMESPACE::Boolean operator==(const XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataFault & type1, const XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataFault & type2)
{
	return (type1.get_value() == type2.get_value());
}

TIBAMX_CORE_NAMESPACE::Boolean operator!=(const XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataFault & type1, const XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataFault & type2)
{
	return (type1.get_value() != type2.get_value());
}
