/*<?xml version="1.0" encoding="UTF-8" standalone="no"?><header>*/
/* <!-- */
//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.

#include "ApplicationSerializerFactory.h"
/* -->
<includeSection>
<includeType generated="YES" name="xsd_java_io_xsd/IOException">
<!--*/
#include "xsd_java_io_xsd/IOException.h"
/*-->
</includeType>
<includeType generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/RemoteExceptionElement">
<!--*/
#include "xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/RemoteExceptionElement.h"
/*-->
</includeType>
<includeType generated="YES" name="xsd_java_rmi_xsd/RemoteException">
<!--*/
#include "xsd_java_rmi_xsd/RemoteException.h"
/*-->
</includeType>
<includeType generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressRequestElement">
<!--*/
#include "xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressRequestElement.h"
/*-->
</includeType>
<includeType generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressRequest">
<!--*/
#include "xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressRequest.h"
/*-->
</includeType>
<includeType generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/Exception">
<!--*/
#include "xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/Exception.h"
/*-->
</includeType>
<includeType generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressResponse">
<!--*/
#include "xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressResponse.h"
/*-->
</includeType>
<includeType generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressResponseElement">
<!--*/
#include "xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressResponseElement.h"
/*-->
</includeType>
<includeType generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/AddressRequestResponseElement">
<!--*/
#include "xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/AddressRequestResponseElement.h"
/*-->
</includeType>
</includeSection>
<!-- */

TIBAMX_CORE_NAMESPACE::DeSerializerPtr ApplicationSerializerFactory::getDeserializerFromQName(TIBAMX_CORE_NAMESPACE::QName& qName) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException)
{
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "String") {return &TIBAMX_CORE_NAMESPACE::StringSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Boolean") {return &TIBAMX_CORE_NAMESPACE::BooleanSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Decimal") {return &TIBAMX_CORE_NAMESPACE::DecimalSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Float") {return &TIBAMX_CORE_NAMESPACE::FloatSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Double") {return &TIBAMX_CORE_NAMESPACE::DoubleSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Duration") {return &TIBAMX_CORE_NAMESPACE::DurationSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "DateTime") {return &TIBAMX_CORE_NAMESPACE::DateTimeSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Time") {return &TIBAMX_CORE_NAMESPACE::TimeSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Date") {return &TIBAMX_CORE_NAMESPACE::DateSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GYearMonth") {return &TIBAMX_CORE_NAMESPACE::GYearMonthSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GMonth") {return &TIBAMX_CORE_NAMESPACE::GMonthSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GMonthDay") {return &TIBAMX_CORE_NAMESPACE::GMonthDaySerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GYear") {return &TIBAMX_CORE_NAMESPACE::GYearSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GDay") {return &TIBAMX_CORE_NAMESPACE::GDaySerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "HexBinary") {return &TIBAMX_CORE_NAMESPACE::HexBinarySerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Base64Binary") {return &TIBAMX_CORE_NAMESPACE::Base64BinarySerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "AnyURI") {return &TIBAMX_CORE_NAMESPACE::AnyURISerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "QName") {return &TIBAMX_CORE_NAMESPACE::QNameSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "ID") {return &TIBAMX_CORE_NAMESPACE::IDSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "IDREF") {return &TIBAMX_CORE_NAMESPACE::IDREFSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NormalizedString") {return &TIBAMX_CORE_NAMESPACE::NormalizedStringSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Token") {return &TIBAMX_CORE_NAMESPACE::TokenSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Language") {return &TIBAMX_CORE_NAMESPACE::LanguageSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Name") {return &TIBAMX_CORE_NAMESPACE::NameSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NCName") {return &TIBAMX_CORE_NAMESPACE::NCNameSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NMTOKEN") {return &TIBAMX_CORE_NAMESPACE::NMTokenSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Integer") {return &TIBAMX_CORE_NAMESPACE::IntegerSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NonPositiveInteger") {return &TIBAMX_CORE_NAMESPACE::NonPositiveIntegerSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Long") {return &TIBAMX_CORE_NAMESPACE::LongSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NonNegativeInteger") {return &TIBAMX_CORE_NAMESPACE::NonNegativeIntegerSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NegativeInteger") {return &TIBAMX_CORE_NAMESPACE::NegativeIntegerSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Int") {return &TIBAMX_CORE_NAMESPACE::IntSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "UnsignedLong") {return &TIBAMX_CORE_NAMESPACE::ULongSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "PositiveInteger") {return &TIBAMX_CORE_NAMESPACE::PositiveIntegerSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Short") {return &TIBAMX_CORE_NAMESPACE::ShortSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Byte") {return &TIBAMX_CORE_NAMESPACE::ByteSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "UnsignedInt") {return &TIBAMX_CORE_NAMESPACE::UIntSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "UnsignedShort") {return &TIBAMX_CORE_NAMESPACE::UShortSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "UnsignedByte") {return &TIBAMX_CORE_NAMESPACE::UByteSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "ENTITY") {return &TIBAMX_CORE_NAMESPACE::ENTITYSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "ENTITIES") {return &TIBAMX_CORE_NAMESPACE::ENTITIESSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "IDREFS") {return &TIBAMX_CORE_NAMESPACE::IDREFSSerializer::deserialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NMTOKENS") {return &TIBAMX_CORE_NAMESPACE::NMTokensSerializer::deserialize;}
//	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NOTATION") {return &TIBAMX_CORE_NAMESPACE::NOTATIONSerializer::deserialize;}
	/* -->
	<deserializerGeneration>
	<deserializeBlock generated="YES" name="xsd_java_io_xsd/IOException">
		<!--*/
	if(qName.get_namespace_uri() == "http://io.java/xsd" && qName.get_local_part() == "IOException"){	return &XSD_JAVA_IO_XSD::IOExceptionSerializer::deserialize; }
	/*-->
		</deserializeBlock>
		<deserializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/RemoteExceptionElement">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com" && qName.get_local_part() == "RemoteExceptionElement"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionElementSerializer::deserialize; }
	/*-->
		</deserializeBlock>
		<deserializeBlock generated="YES" name="xsd_java_rmi_xsd/RemoteException">
		<!--*/
	if(qName.get_namespace_uri() == "http://rmi.java/xsd" && qName.get_local_part() == "RemoteException"){	return &XSD_JAVA_RMI_XSD::RemoteExceptionSerializer::deserialize; }
	/*-->
		</deserializeBlock>
		<deserializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressRequestElement">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com/xsd" && qName.get_local_part() == "AddressRequestElement"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_XSD::AddressRequestElementSerializer::deserialize; }
	/*-->
		</deserializeBlock>
		<deserializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressRequest">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com/xsd" && qName.get_local_part() == "AddressRequest"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_XSD::AddressRequestSerializer::deserialize; }
	/*-->
		</deserializeBlock>
		<deserializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/Exception">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com" && qName.get_local_part() == "Exception"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::ExceptionSerializer::deserialize; }
	/*-->
		</deserializeBlock>
		<deserializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressResponse">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com/xsd" && qName.get_local_part() == "AddressResponse"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_XSD::AddressResponseSerializer::deserialize; }
	/*-->
		</deserializeBlock>
		<deserializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressResponseElement">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com/xsd" && qName.get_local_part() == "AddressResponseElement"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_XSD::AddressResponseElementSerializer::deserialize; }
	/*-->
		</deserializeBlock>
		<deserializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/AddressRequestResponseElement">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com" && qName.get_local_part() == "addressRequestResponseElement"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::AddressRequestResponseElementSerializer::deserialize; }
	/*-->
		</deserializeBlock>
		</deserializerGeneration>
	<!-- */
	throw new TIBAMX_CORE_NAMESPACE::TibcoRuntimeException("ApplicationSerializerFactory::getDeserializerFromQName : No deserializer found");
}
TIBAMX_CORE_NAMESPACE::SerializerPtr ApplicationSerializerFactory::getSerializerFromQName(TIBAMX_CORE_NAMESPACE::QName& qName) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException)
{
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "String") {return &TIBAMX_CORE_NAMESPACE::StringSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Boolean") {return &TIBAMX_CORE_NAMESPACE::BooleanSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Decimal") {return &TIBAMX_CORE_NAMESPACE::DecimalSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Float") {return &TIBAMX_CORE_NAMESPACE::FloatSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Double") {return &TIBAMX_CORE_NAMESPACE::DoubleSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Duration") {return &TIBAMX_CORE_NAMESPACE::DurationSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "DateTime") {return &TIBAMX_CORE_NAMESPACE::DateTimeSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Time") {return &TIBAMX_CORE_NAMESPACE::TimeSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Date") {return &TIBAMX_CORE_NAMESPACE::DateSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GYearMonth") {return &TIBAMX_CORE_NAMESPACE::GYearMonthSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GMonth") {return &TIBAMX_CORE_NAMESPACE::GMonthSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GMonthDay") {return &TIBAMX_CORE_NAMESPACE::GMonthDaySerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GYear") {return &TIBAMX_CORE_NAMESPACE::GYearSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "GDay") {return &TIBAMX_CORE_NAMESPACE::GDaySerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "HexBinary") {return &TIBAMX_CORE_NAMESPACE::HexBinarySerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Base64Binary") {return &TIBAMX_CORE_NAMESPACE::Base64BinarySerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "AnyURI") {return &TIBAMX_CORE_NAMESPACE::AnyURISerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "QName") {return &TIBAMX_CORE_NAMESPACE::QNameSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "ID") {return &TIBAMX_CORE_NAMESPACE::IDSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "IDREF") {return &TIBAMX_CORE_NAMESPACE::IDREFSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NormalizedString") {return &TIBAMX_CORE_NAMESPACE::NormalizedStringSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Token") {return &TIBAMX_CORE_NAMESPACE::TokenSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Language") {return &TIBAMX_CORE_NAMESPACE::LanguageSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Name") {return &TIBAMX_CORE_NAMESPACE::NameSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NCName") {return &TIBAMX_CORE_NAMESPACE::NCNameSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NMTOKEN") {return &TIBAMX_CORE_NAMESPACE::NMTokenSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Integer") {return &TIBAMX_CORE_NAMESPACE::IntegerSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NonPositiveInteger") {return &TIBAMX_CORE_NAMESPACE::NonPositiveIntegerSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Long") {return &TIBAMX_CORE_NAMESPACE::LongSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NonNegativeInteger") {return &TIBAMX_CORE_NAMESPACE::NonNegativeIntegerSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NegativeInteger") {return &TIBAMX_CORE_NAMESPACE::NegativeIntegerSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Int") {return &TIBAMX_CORE_NAMESPACE::IntSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "UnsignedLong") {return &TIBAMX_CORE_NAMESPACE::ULongSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "PositiveInteger") {return &TIBAMX_CORE_NAMESPACE::PositiveIntegerSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Short") {return &TIBAMX_CORE_NAMESPACE::ShortSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "Byte") {return &TIBAMX_CORE_NAMESPACE::ByteSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "UnsignedInt") {return &TIBAMX_CORE_NAMESPACE::UIntSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "UnsignedShort") {return &TIBAMX_CORE_NAMESPACE::UShortSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "UnsignedByte") {return &TIBAMX_CORE_NAMESPACE::UByteSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "ENTITY") {return &TIBAMX_CORE_NAMESPACE::ENTITYSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "ENTITIES") {return &TIBAMX_CORE_NAMESPACE::ENTITIESSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "IDREFS") {return &TIBAMX_CORE_NAMESPACE::IDREFSSerializer::serialize;}
	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && qName.get_local_part() == "NMTOKENS") {return &TIBAMX_CORE_NAMESPACE::NMTokensSerializer::serialize;}
//	if(qName.get_namespace_uri() == "http://www.w3.org/2001/XMLSchema" && dqName.get_local_part() == "NOTATION") {return &TIBAMX_CORE_NAMESPACE::NOTATIONSerializer::serialize;}
	/* -->
	<serializerGeneration>
	<serializeBlock generated="YES" name="xsd_java_io_xsd/IOException">
		<!--*/
	if(qName.get_namespace_uri() == "http://io.java/xsd" && qName.get_local_part() == "IOException"){	return &XSD_JAVA_IO_XSD::IOExceptionSerializer::serialize; }
	/*-->
		</serializeBlock>
		<serializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/RemoteExceptionElement">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com" && qName.get_local_part() == "RemoteExceptionElement"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionElementSerializer::serialize; }
	/*-->
		</serializeBlock>
		<serializeBlock generated="YES" name="xsd_java_rmi_xsd/RemoteException">
		<!--*/
	if(qName.get_namespace_uri() == "http://rmi.java/xsd" && qName.get_local_part() == "RemoteException"){	return &XSD_JAVA_RMI_XSD::RemoteExceptionSerializer::serialize; }
	/*-->
		</serializeBlock>
		<serializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressRequestElement">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com/xsd" && qName.get_local_part() == "AddressRequestElement"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_XSD::AddressRequestElementSerializer::serialize; }
	/*-->
		</serializeBlock>
		<serializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressRequest">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com/xsd" && qName.get_local_part() == "AddressRequest"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_XSD::AddressRequestSerializer::serialize; }
	/*-->
		</serializeBlock>
		<serializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/Exception">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com" && qName.get_local_part() == "Exception"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::ExceptionSerializer::serialize; }
	/*-->
		</serializeBlock>
		<serializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressResponse">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com/xsd" && qName.get_local_part() == "AddressResponse"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_XSD::AddressResponseSerializer::serialize; }
	/*-->
		</serializeBlock>
		<serializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress_xsd/AddressResponseElement">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com/xsd" && qName.get_local_part() == "AddressResponseElement"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_XSD::AddressResponseElementSerializer::serialize; }
	/*-->
		</serializeBlock>
		<serializeBlock generated="YES" name="xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/AddressRequestResponseElement">
		<!--*/
	if(qName.get_namespace_uri() == "http://companyaddress.iqatest.ejbbt.amx.tibco.com" && qName.get_local_part() == "addressRequestResponseElement"){	return &XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::AddressRequestResponseElementSerializer::serialize; }
	/*-->
		</serializeBlock>
		</serializerGeneration>
	<!-- */
	throw new TIBAMX_CORE_NAMESPACE::TibcoRuntimeException("ApplicationSerializerFactory::getSerializerFromQName : No serializer found");
}
/* --> */
//</header>
