/*<?xml version="1.0" encoding="UTF-8"?><header>*/
/* <!-- */
//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.

#ifndef APPLICATIN_SERIALIZER_FACTORY_H_
#define APPLICATIN_SERIALIZER_FACTORY_H_

#include "application/TibAmxApplicationDefinitions.h"
#include "tibamx/databinding/cppdom/serializers/Serializers.h"
#include "tibamx/databinding/cppdom/xml/TibcoXmlTypes.h"
#include "tibamx/databinding/cppdom/xml/IntegerTypes.h"

class ApplicationSerializerFactory
{

public:

	static TIBAMX_CORE_NAMESPACE::SerializerPtr getSerializerFromQName(
								TIBAMX_CORE_NAMESPACE::QName& qName) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException);
								
	static TIBAMX_CORE_NAMESPACE::DeSerializerPtr getDeserializerFromQName(
								TIBAMX_CORE_NAMESPACE::QName& qName) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException);
	
};
#endif // APPLICATIN_TYPE_FACTORY_H_
/* --> */
//</header>
