/*<?xml version="1.0" encoding="UTF-8"?><header>*/
/* <!-- */
//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.


#ifndef TIBAMX_APPLICATION_DEFINITIONS_H_
#define TIBAMX_APPLICATION_DEFINITIONS_H_

#include "tibamx/utils/TibAmxVersion.h"

#define TIBCO_AMX_USER_VERSION_MAJOR 3
#define TIBCO_AMX_USER_VERSION_MINOR 1
#define TIBCO_AMX_USER_VERSION_PATCH 0

#define TIBCO_AMX_USER_FULLVERSIONNUM INVK_TIBCO_CAT3_SEP_NIL(TIBCO_AMX_USER_VERSION_MAJOR,TIBCO_AMX_USER_VERSION_MINOR,TIBCO_AMX_USER_VERSION_PATCH)

#endif
