//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
  
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT. 
#ifndef XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_REMOTEEXCEPTIONFAULT_H_
#define XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_REMOTEEXCEPTIONFAULT_H_

#include "application/TibAmxApplicationDefinitions.h"
#include "tibamx/databinding/cppdom/xml/TibcoXmlTypes.h"
#include "tibamxcpp/utils/TibAmxCppDefinitions.h"
#include "tibamx/databinding/cppdom/serializers/Context.h"
#include "tibamx/core/TibcoRuntimeException.h" 
#include "xsd_com_tibco_amx_ejbbt_iqatest_companyaddress/RemoteExceptionElement.h"

namespace XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS
{
	class RemoteExceptionFault
	{
	public:

		RemoteExceptionFault();
		RemoteExceptionFault(XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionElement& value) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException);
		RemoteExceptionFault(const RemoteExceptionFault &);
		virtual ~RemoteExceptionFault();

		const XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionElement& get_value() const;
		void set_value(XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionElement& value);

		RemoteExceptionFault & operator=(const RemoteExceptionFault &);

	private:
		XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionElement* t_value;
	};

	class RemoteExceptionFaultSerializer
	{
	public:
		static void serialize(XERCES_CPP_NAMESPACE::DOMElement* element, const void* input, Context* context) throw (TIBAMX_CORE_NAMESPACE::ServiceDataException);
		static void* deserialize(TIBAMX_CORE_NAMESPACE::DOMElementIterator& elementItr, void* returnValue, Context* context) throw (TIBAMX_CORE_NAMESPACE::ServiceDataException);
	};
}

TIBAMX_CORE_NAMESPACE::Boolean operator==(const XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionFault &, const XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionFault &);
TIBAMX_CORE_NAMESPACE::Boolean operator!=(const XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionFault &, const XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionFault &);

#endif
