/*<?xml version="1.0" encoding="UTF-8" standalone="no"?><header>*/
/* <!-- */
//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.
#ifndef BAT811CPPPROJECT_NAMESPACE_SAMPLEIMPL_H_
#define BAT811CPPPROJECT_NAMESPACE_SAMPLEIMPL_H_

#include "AbstractSampleImpl.h"
#define BAT811CPPPROJECT_NAMESPACE SampleNamespace
/* -->
<includeSection>
</includeSection>
<!-- */
namespace BAT811CPPPROJECT_NAMESPACE
{
	class SampleImpl : public AbstractSampleImpl
			/* --><InheritanceDefinitions>
			</InheritanceDefinitions><!-- */
	{

	public:
		SampleImpl() {}
		virtual ~SampleImpl() {}

		/*	
		 * Add initialization code here. This method is called once during component initialization.
		 */
		virtual void init() throw (TIBAMX_CORE_NAMESPACE::ApplicationException);

		/*	
		 * Add finalization code here. This method is called once during component destruction.
		 */
		virtual void destroy() throw (TIBAMX_CORE_NAMESPACE::ApplicationException);

		/* -->
		<publicSection>
		<service generated="YES" name="WSDL_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::AddressRemotePortTypeService">
		<!--*/
		XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::AddressRequestResponseElement*  addressRequest(const XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS_XSD::AddressRequest& addressRequestargs0) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException ,XSD_COM_TIBCO_AMX_EJBBT_IQATEST_COMPANYADDRESS::RemoteExceptionFault);

		/*-->
		</service>
		</publicSection>
		<!-- */

	}; //END of SampleImpl
} //END of BAT811CPPPROJECT_NAMESPACE

#endif
/* --> */
//</header>
