//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.    
#ifndef SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE_sampleimpl_applicationfactory_h_
#define SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE_sampleimpl_applicationfactory_h_

#if defined(WIN32) || defined (_WINDOWS)
#pragma warning(disable: 4786)
#endif 

#include <iostream>
#include "application/TibAmxApplicationDefinitions.h"
#include "application/SampleImpl.h"
#include "tibamxcpp/core/Application.h"
#include "tibamxcpp/core/Wrapper.h"
#include "tibamxcpp/core/ApplicationFactory.h"
#define SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE SampleNamespace

namespace SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE
{
	class SampleImpl_ApplicationFactory : public TIBAMX_CPP_NAMESPACE::ApplicationFactory
	{
	public:

		SampleImpl_ApplicationFactory();

		virtual ~SampleImpl_ApplicationFactory();

		/*	
		 * This method returns version of the generated code.
		 */
		virtual int getCodeVersion() const;
		
		virtual TIBAMX_CPP_NAMESPACE::Wrapper* getServiceWrapper() const;
		virtual TIBAMX_CPP_NAMESPACE::Wrapper* getReferenceWrapper(const std::string& referenceName) const;
		
	};
} //Closing of SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE
#endif
