/*<?xml version="1.0" encoding="UTF-8" standalone="no"?><header>*/
/* <!-- */
//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.

#ifndef SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE_sampleimpl_wrapper_h_
#define SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE_sampleimpl_wrapper_h_

#if defined(WIN32) || defined (_WINDOWS)
#pragma warning(disable: 4786)
#endif 

#include "application/TibAmxApplicationDefinitions.h"
#include "application/SampleImpl.h"
#include "tibamx/databinding/cppdom/xml/IntegerTypes.h"
#include "tibamxcpp/core/Wrapper.h"
#include "tibamxcpp/core/Application.h"
#include "tibamx/databinding/cppdom/serializers/Serializers.h"
#include <xercesc/dom/DOM.hpp>
#define SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE SampleNamespace

namespace SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE
{
	class SampleImpl_Wrapper : public TIBAMX_CPP_NAMESPACE::Wrapper
	{
	public:

		SampleImpl_Wrapper(TIBAMX_CPP_NAMESPACE::Application& appImpl) : TIBAMX_CPP_NAMESPACE::Wrapper(appImpl){}

		~SampleImpl_Wrapper(){}
				
		virtual void invoke(TIBAMX_CPP_NAMESPACE::Operation& operation) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException);
		
	private:
		/* -->
		<constantVariablesSection>
		<service generated="YES" name="WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::AllMEPsWSDLFileService">
		<!--*/

		static const XMLCh* ALLMEPSWSDLFILE_TNS_IN;
		static const XMLCh* ALLMEPSWSDLFILE_HTTP___WWW_EXAMPLE_ORG_ALLMEPSWSDLFILE_;
		static const XMLCh* ALLMEPSWSDLFILE_TNS_INOUTFAULT;
		static const XMLCh* ALLMEPSWSDLFILE_TNS_INOUT;
		static const XMLCh* ALLMEPSWSDLFILE_NEWOPERATION_DATA_BINARY;
		static const XMLCh* ALLMEPSWSDLFILE_TNS_NEWOPERATIONRESPONSE_DATA_TEXT;
		static const XMLCh* ALLMEPSWSDLFILE_TNS_NEWOPERATIONFAULT_DATA;
		static const XMLCh* ALLMEPSWSDLFILE_TNS_NEWOPERATIONRESPONSE_DATA;
		static const XMLCh* ALLMEPSWSDLFILE_NEWOPERATION_DATA;
		/*-->
		</service>
		</constantVariablesSection>
		<!-- */
	};
} //Closing of SAMPLE_BAT7_1_CPP1IMPL_NAMESPACE
#endif // SampleImpl_Wrapper_h
/* --> */
//</header>
