//(c) Copyright 2008, TIBCO Software Inc.  All rights reserved.
//LEGAL NOTICE:  This source code is provided to specific authorized end
//users pursuant to a separate license agreement.  You MAY NOT use this
//source code if you do not have a separate license from TIBCO Software
//Inc.  Except as expressly set forth in such license agreement, this
//source code, or any portion thereof, may not be used, modified,
//reproduced, transmitted, or distributed in any form or by any means,
//electronic or mechanical, without written permission from  TIBCO
//Software Inc.
//THIS CODE HAS BEEN GENERATED BY A TOOL. DO NOT EDIT.    
#ifndef WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE_ALLMEPSWSDLFILEALLMEPSWSDLFILEPROXY_H_
#define WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE_ALLMEPSWSDLFILEALLMEPSWSDLFILEPROXY_H_
#include "application/TibAmxApplicationDefinitions.h"
#include "tibamx/databinding/cppdom/xml/TibcoXmlTypes.h"
#include "tibamx/databinding/cppdom/xml/IntegerTypes.h"
#include "tibamxcpp/utils/TibAmxCppDefinitions.h"
#include "tibamx/core/TibcoRuntimeException.h"
#include "tibamxcpp/core/CppMessageProxy.h"
#include "tibamxcpp/core/Application.h"
#include "tibamx/databinding/cppdom/serializers/Serializers.h"
#include "tibamx/databinding/cppdom/serializers/ArtifactSerializer.h"
#include <xercesc/dom/DOM.hpp>

#include "xsd_org_example_www_allmepswsdlfile/NewOperationFault_dataFault.h"
#include "xsd_org_example_www_allmepswsdlfile/NewOperation_dataElement.h"
#include "xsd_org_example_www_allmepswsdlfile/NewOperationResponse_dataElement.h"

namespace WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE
{
	class AllMEPsWSDLFileAllMEPsWSDLFileProxy : public TIBAMX_CPP_NAMESPACE::CppMessageProxy
	{
	public:
		AllMEPsWSDLFileAllMEPsWSDLFileProxy() {}
		virtual ~AllMEPsWSDLFileAllMEPsWSDLFileProxy() {}

		//Operations within Service Class.
		virtual void in(const XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperation_dataElement& parameters) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException );

		virtual XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationResponse_dataElement*  inOut(const XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperation_dataElement& parameters) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException );

		virtual TIBAMX_CORE_NAMESPACE::String*  inOutFault(const TIBAMX_CORE_NAMESPACE::Base64Binary& parameters) throw (TIBAMX_CORE_NAMESPACE::TibcoRuntimeException ,XSD_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE::NewOperationFault_dataFault);

	private:

		static const XMLCh* ALLMEPSWSDLFILE_TNS_IN;
		static const XMLCh* ALLMEPSWSDLFILE_HTTP___WWW_EXAMPLE_ORG_ALLMEPSWSDLFILE_;
		static const XMLCh* ALLMEPSWSDLFILE_TNS_INOUTFAULT;
		static const XMLCh* ALLMEPSWSDLFILE_TNS_INOUT;
		static const XMLCh* ALLMEPSWSDLFILE_TNS_NEWOPERATION_DATA;
		static const XMLCh* ALLMEPSWSDLFILE_NEWOPERATIONRESPONSE_DATA_TEXT;
		static const XMLCh* ALLMEPSWSDLFILE_NEWOPERATIONRESPONSE_DATA;
		static const XMLCh* ALLMEPSWSDLFILE_NEWOPERATIONFAULT_DATA;
		static const XMLCh* ALLMEPSWSDLFILE_TNS_NEWOPERATION_DATA_BINARY;
	}; //END of AllMEPsWSDLFileAllMEPsWSDLFileProxy
} //END of WSDL_ORG_EXAMPLE_WWW_ALLMEPSWSDLFILE

#endif
